import { defineBuildConfig } from 'unbuild'

export default defineBuildConfig({
  entries: [
    // Build ESM version with .mjs extension
    {
      builder: 'mkdist',
      input: './src',
      outDir: './dist',
      format: 'esm',
      ext: 'mjs',
      declaration: true,
    },
    // Build CJS version with .cjs extension
    {
      builder: 'mkdist',
      input: './src',
      outDir: './dist',
      format: 'cjs',
      ext: 'cjs',
      declaration: false, // Declarations are already generated by the ESM pass
    },
  ],

  outDir: 'dist',
  declaration: true,

  rollup: {
    emitCJS: true,
    inlineDependencies: false,
    esbuild: {
      minify: false,
      keepNames: true,
    },
  },

  clean: true,
})
